# Generated by Django 3.2.4 on 2021-12-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContestAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestid', models.IntegerField()),
                ('announcement', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ContestBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestid', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('problemrank', models.IntegerField()),
                ('result', models.IntegerField()),
                ('submittime', models.BigIntegerField()),
                ('submitid', models.IntegerField()),
                ('rating', models.IntegerField(default=1500)),
            ],
        ),
        migrations.CreateModel(
            name='ContestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestid', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
                ('title', models.CharField(default='提问', max_length=50)),
                ('problem', models.CharField(default='ALL', max_length=500)),
                ('message', models.CharField(max_length=500)),
                ('huifu', models.CharField(default='No respones', max_length=500)),
                ('time', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(default=1500)),
            ],
        ),
        migrations.CreateModel(
            name='ContestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='admin', max_length=50)),
                ('title', models.CharField(default='contest', max_length=50)),
                ('level', models.IntegerField(default='contest level', max_length=50)),
                ('des', models.CharField(default='contest des', max_length=50)),
                ('note', models.CharField(default='contest note', max_length=50)),
                ('type', models.CharField(default='ACM', max_length=50)),
                ('auth', models.IntegerField(default='1', max_length=50)),
                ('clonefrom', models.IntegerField(default='-1', max_length=50)),
                ('begintime', models.DateTimeField()),
                ('lasttime', models.IntegerField(default='18000')),
            ],
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestid', models.IntegerField()),
                ('problemid', models.CharField(max_length=100)),
                ('problemtitle', models.CharField(default='uname', max_length=500)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContestRatingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestid', models.IntegerField()),
                ('contestname', models.CharField(max_length=100)),
                ('contesttime', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=50)),
                ('lastrating', models.IntegerField(default=0)),
                ('ratingchange', models.IntegerField(default=0)),
                ('currentrating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContestRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestid', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContestTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestid', models.IntegerField()),
                ('value', models.TextField(default='暂无数据！')),
            ],
        ),
    ]
