# Generated by Django 3.2.4 on 2021-12-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestBoardTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('contestid', models.IntegerField()),
                ('score', models.IntegerField()),
                ('time', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ContestChoiceProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContestId', models.IntegerField()),
                ('ChoiceProblemId', models.CharField(max_length=50)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContestComingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ojName', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('startTime', models.BigIntegerField()),
                ('endTime', models.BigIntegerField()),
                ('contestName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StudentChoiceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('realname', models.CharField(default='', max_length=100)),
                ('number', models.CharField(default='', max_length=100)),
                ('contestid', models.CharField(default='', max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('answer_detail', models.TextField(default='')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='contestinfo',
            name='classes',
            field=models.CharField(default='All', max_length=500),
        ),
        migrations.AddField(
            model_name='contestinfo',
            name='iprange',
            field=models.CharField(default='iprange', max_length=2000),
        ),
        migrations.AddField(
            model_name='contestinfo',
            name='lockboard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contestinfo',
            name='locktime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contestinfo',
            name='oj',
            field=models.CharField(default='CDUOJ', max_length=50),
        ),
        migrations.AlterField(
            model_name='contestinfo',
            name='auth',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='contestinfo',
            name='clonefrom',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='contestinfo',
            name='des',
            field=models.CharField(default='contest des', max_length=500),
        ),
        migrations.AlterField(
            model_name='contestinfo',
            name='lasttime',
            field=models.IntegerField(default=18000),
        ),
        migrations.AlterField(
            model_name='contestinfo',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contestinfo',
            name='note',
            field=models.CharField(default='contest note', max_length=500),
        ),
    ]
