# Generated by Django 3.2.4 on 2021-12-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_rename_result_contestboard_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestid', models.IntegerField()),
                ('notice', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='ContestAnnouncement',
        ),
    ]
