# Generated by Django 3.2.4 on 2021-12-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('regtime', models.DateTimeField(auto_now=True)),
                ('logintime', models.DateTimeField(auto_now=True)),
                ('school', models.CharField(default='', max_length=50)),
                ('course', models.CharField(default='', max_length=50)),
                ('classes', models.CharField(default='', max_length=50)),
                ('number', models.CharField(default='', max_length=50)),
                ('realname', models.CharField(max_length=50)),
                ('qq', models.CharField(default='', max_length=50, null=True)),
                ('email', models.CharField(default='', max_length=50, null=True)),
                ('type', models.IntegerField(default=1)),
            ],
        ),
    ]
