# Generated by Django 3.2.4 on 2021-12-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ac', models.IntegerField(default=0)),
                ('submit', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('des', models.CharField(max_length=50, null=True)),
                ('rating', models.IntegerField(default=1500)),
                ('acpro', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLoginData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('ip', models.CharField(default='unknow', max_length=50, null=True)),
                ('logintime', models.DateTimeField(auto_now=True)),
                ('msg', models.TextField(null=True)),
            ],
        ),
    ]
